- Python is slow

- But numpy is made in C which makes it faster

- Topics covered:
    - Variables
    - Data types
    - Lists
    - Loops
    - Functions
    - Indexing

In [3]:
import numpy as np # you need to install it through terminal

In [5]:
my_list = [1,2,3,4]

In [6]:
print(my_list)

[1, 2, 3, 4]


In [14]:
array = np.array([1,2,3,4]) # this is array

In [15]:
print(array)

[1 2 3 4]


In [16]:
print(type(array))

<class 'numpy.ndarray'>


In [17]:
array = array*2 # this multiplies array elements by 2 but in lists it will duplicate elements

In [18]:
print(array)

[2 4 6 8]


### Multidimensional array

In [20]:
multi_array = np.array([[1,2,3,4],[5,6,7,8], [9, 10, 11, 12]])

In [21]:
print(multi_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
print(array.ndim)

1


In [23]:
print(multi_array.ndim)

2


In [24]:
multi_array_3 = np.array([[[1,2],[3,4], [5,6]],
                         [[7,8],[9,0], [1,2]],
                         [[3,4],[5,6], [7,8]]])

In [25]:
print(multi_array_3)

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 0]
  [1 2]]

 [[3 4]
  [5 6]
  [7 8]]]


In [26]:
print(multi_array_3.ndim)

3


**shape**
- this returns depth, number of rows, and number of columns depending on the array.

In [27]:
print(multi_array_3.shape)

(3, 3, 2)


In [28]:
print(multi_array.shape)

(3, 4)


In [29]:
print(array.shape)

(4,)


- in list we use chain indexing, which is l[0][0][0]

- in numoy arrays also we can do this

- But we have multidimensional indexing
    - In this we write every index in single [] but they are seperated by commas
- Multidimensional indexing is faster than chain indexing

In [31]:
print(multi_array_3[0][0][0]) # chain indexing

1


In [33]:
print(multi_array_3[0,0,1]) # multidimensional index

2


In [34]:
print(multi_array[1,2])

7


### Slicing

In [35]:
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

In [41]:
# array[start:end:step]
array[0:4:2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [42]:
array[::-1]

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [47]:
array[:,0] #column selection: returns only columns

array([ 1,  5,  9, 13])

In [48]:
print(array[:,2])

[ 3  7 11 15]


In [49]:
print(array[:,0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [50]:
print(array[:,1:4])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [55]:
print(array[0:2,0:2])

[[1 2]
 [5 6]]


In [58]:
print(array[0:2,2:])

[[3 4]
 [7 8]]


### Arithmetic

**Scalar Arithmetic**
- means single value i.e, applying single value to each element of array

In [61]:
array = np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [62]:
print(array+1)

[2 3 4 5]


In [63]:
print(array-1)

[0 1 2 3]


In [64]:
print(array*2)

[2 4 6 8]


In [68]:
print(array/3)

[0.33333333 0.66666667 1.         1.33333333]


In [69]:
print(array**4)

[  1  16  81 256]


In [71]:
print(array//2)

[0 1 1 2]


In [72]:
array

array([1, 2, 3, 4])

**Vectorized math functions**

- Vector means single dimension

- We can apply a function to every element of the array

In [73]:
print(np.sqrt(array))

[1.         1.41421356 1.73205081 2.        ]


In [75]:
radii = np.array([1,2,3])

In [77]:
# finding area of circle

print(np.pi*radii**2)

[ 3.14159265 12.56637061 28.27433388]


**Element-wise arithmetic**

- to apply operation between single elements of two different arrays

In [78]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [79]:
print(a1+a2)

[5 7 9]


In [80]:
print(a1-a2)

[-3 -3 -3]


In [81]:
print(a1*a2)

[ 4 10 18]


In [82]:
print(a1/a2)

[0.25 0.4  0.5 ]


In [83]:
print(a1**a2)

[  1  32 729]


**Comparison operation**

In [84]:
scores = np.array([91,55,100,73,82,64])

In [85]:
print(scores==100)

[False False  True False False False]


In [87]:
print(scores>=60)

[ True False  True  True  True  True]


In [88]:
print(scores<60)

[False  True False False False False]


In [90]:
scores[scores<60] = 0

In [91]:
print(scores)

[ 91   0 100  73  82  64]


### broadcasting

- Broadcasting allows numpy to perform operations on arrays with differrent shapes by virtually expanding dimensions, so they match the larger array's shape

- The dimensions have same size OR one of the dimensions has a size of 1

In [92]:
a1 = np.array([[1,2,3,4]])
a2 = np.array([[1],[2],[3],[4]])

In [93]:
print(a1.shape)
print(a2.shape)

(1, 4)
(4, 1)


In [94]:
print(a1 * a2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [95]:
a3 = np.array([[1,2,3,4],[5,6,7,8]])
a4 = np.array([[1],[2],[3],[4]])

In [98]:
print(a3*a4)

ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

### Aggregate functions

- summarize data and typically returns a single value

In [101]:
array = np.array([[1,2,3,4,5],
               [6,7,8,9,10]])

In [102]:
print(np.sum(array))

55


In [103]:
print(np.mean(array))

5.5


In [104]:
print(np.std(array)) #standard deviation

2.8722813232690143


In [105]:
# variance
print(np.var(array))

8.25


In [106]:
print(np.min(array))

1


In [107]:
print(np.max(array))

10


In [110]:
print(np.argmin(array)) #returns index of least value

0


In [111]:
print(np.argmax(array)) #returns index of largest value

9


In [114]:
print(np.sum(array, axis=0)) #sum of columns

[ 7  9 11 13 15]


In [115]:
print(np.sum(array, axis=1)) #sum of rows

[15 40]


### filtering

- selecting elements from array which match given condition

In [116]:
ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])

In [117]:
teenagers = ages[ages<18]

In [118]:
print(teenagers)

[17 16 15]


In [124]:
adults = ages[(ages >= 18) & (ages<65)]

In [125]:
print(adults)

[21 19 20 30 18 39 22 18 19 20 21]


In [126]:
adults = ages[(ages < 18) | (ages>=65)]

In [127]:
print(adults)

[17 16 65 15 99]


In [128]:
seniors = ages[ages>=65]

In [129]:
print(seniors)

[65 99]


In [130]:
evens = ages[ages%2==0]

In [131]:
print(evens)

[20 16 30 18 22 18 20]


In [134]:
# to preserve the shape

adults = np.where(ages>=18, ages, 0)

In [135]:
print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


### Random numbers

In [136]:
array = np.random.default_rng()

In [140]:
print(array.integers(1,7))

4


In [141]:
print(array.integers(low = 1, high = 101, size = (4,5)))

[[48 44 12 58 30]
 [68 95 65 70 33]
 [47 40 46 47 33]
 [66 16 10  9 34]]


In [168]:
# to produce same results use seed
rng = np.random.default_rng(seed=1)
print(rng.integers(low = 1, high = 101, size = (3,2)))

[[48 52]
 [76 96]
 [ 4 15]]


In [164]:
print(np.random.uniform(-1,1, size=3))

[ 0.51477887  0.65133231 -0.35759425]


In [171]:
np.random.seed(seed=1)
print(np.random.uniform(low=-1, high=1, size=(3,2)))

[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


In [176]:
rng = np.random.default_rng()
array = np.array([1,2,3,4,5])
rng.shuffle(array)
print(array)

[5 3 1 2 4]


In [177]:
fruits = np.array(['apple','orange','banana','coconut','pineapple'])

In [178]:
print(fruits)

['apple' 'orange' 'banana' 'coconut' 'pineapple']


In [185]:
fruit = rng.choice(fruits)
print(fruit)

coconut


In [190]:
fruit = rng.choice(fruits, size = 3)
print(fruit)

['pineapple' 'coconut' 'banana']


In [191]:
fruits = np.array(['🍎','🍊','🍌','🥥','🍍'])

In [197]:
fruit = rng.choice(fruits, size = (3,3))
print(fruit)

[['🍊' '🥥' '🍌']
 ['🍎' '🍌' '🍍']
 ['🍊' '🥥' '🍎']]
